### ISSUE TITLE
Optional link parameter

### ISSUE THREAD

**Issue by ericflo** [jboesch/Gritter#1]
It would be great to be able to make the notifications actionable, so that clicking on the body of the notification (not the X) will take you to some URL.  In other words, I'd like to be able to do something like this:

```
$.gritter.add({
    title: 'New Comment',
    text: 'There has been a new comment on your post.',
    link: '/posts/1/',
    sticky: true
})
```

In this example, If the user clicked on this sticky notification, it would take them to /posts/1/.

Is this something that you would consider adding?

**Comment by jboesch** [comment]
Right now links are allowed in the title and text fields.  I would rather keep it to that than have 2 places where people could provide links.

Here's an example that would work today:

<pre><code>
title: '<a href="/posts/1">New comment</a>',
text: '<a href="/posts/1/">There has been a new comment on your post</a>'
</code>
</pre>

**Comment by ericflo** [comment]
Ahh that's awesome, I didn't even think about adding a link _inside_ the title and text fields.  I think that's probably going to be fine for my use case.  Thanks!
