### ISSUE TITLE
Problem with jQuery 1.4.2

### ISSUE THREAD

**Issue by mdebureaux** [jboesch/Gritter#2]
Hello,

Gritter seems not working with jQuery 1.4.2, the mouse pointer flinks on the close button and unable to close the notification after all.

All the best.

**Comment by jboesch** [comment]
Hey Mark,

Instead of replying to your email, I'll just reply here.  Could you provide me a link to the example you're seeing?  I just tried my gritter demo from github with 1.4.2 and it seems to be working fine for me.

**Comment by mdebureaux** [comment]
I'm unable to show you the problem because it needs an authenfication, but I had to precise that the problems appears when including Gritted inside a GreaseMonkey/Chrome userscript with jQuery 1.4.2, not for a website.

I'm pretty sure there is a problem betweek jQuery and Gritter because downgrading jQuery to 1.3.2 solve the problem. We use your programs too in a web game and we faced the same problem, if necessary I could send you the whole code.

**Comment by jboesch** [comment]
This seems to be a problem in jQuery.  Not sure what changed.  You're right, worked fine in 1.3.2 but not in 1.4.2.  Could you email me the entire code base? Not sure I can fix it but I'll take a look.

**Comment by mdebureaux** [comment]
I sent you one of our script by mail. Have fun. ;)

**Comment by jboesch** [comment]
Closed.
