### ISSUE TITLE
Page jumps to the top

### ISSUE THREAD

**Issue by gfrobenius** [jboesch/Gritter#26]
Awesome plugin!
If you have a long page that has a vertical scroll bar and a action you down there triggers a gritter, gritter causes the page to scroll back to the top.  It would be nice to have the page just stay where it is.  Some actions on my site cause a visual change on pages down there but when gritter causes the page to jump to the top you miss seeing those changes.  You have to scroll back down to see them.

**Comment by jboesch** [comment]
Can you link me to an example you're experiencing?
