### ISSUE TITLE
HTTP 404

### ISSUE THREAD

**Issue by davidhorsak** [jboesch/Gritter#3]
Hi. I was struggling with HTTP 404 error caused by gritter's CSS. On line 33 the stylesheet tries to load the "." path which is the folder of the css. Some applications, for example my rails one, when the stylesheet tries to load the path returns the mentioned error. It is deeply discussed here http://duckranger.com/2010/06/getting-404-with-jquery-gritter/ Please check it out and fix it for future comers. Thanks

**Comment by jboesch** [comment]
Thanks for the heads up. Just fixed this and pushed: 
https://github.com/jboesch/Gritter/commit/20bc6e0ea44689d4fa4cb9f7ea0adf42b313f7c8
