### ISSUE TITLE
Position not working

### ISSUE THREAD

**Issue by arvinsim** [jboesch/Gritter#46]
I have this very simple code

```
$.gritter.add({
        'title': 'Test',
        'text': 'test',
        'position': 'bottom-right',
        'sticky': false 
});
```

The problem is that it is not showing on the bottom right. It is still showing on the upper right.

In fact, I tried upper-left, bottom-left and bottom-right and it is still on the upper right.

**Comment by arvinsim** [comment]
Nevermind. I think I can't define it in the params. I have to define it in the extend

```
$.extend($.gritter.options, { 
      position: 'bottom-right',
});
```

Although it would be mighty convenient if we can define it in the params.

**Comment by jboesch** [comment]
Until there is more of a demand for that kind of flexibility, I'm going to keep as in and close it. Thanks!

**Comment by miltonmagalhaes** [comment]
the solution is in the adaptation of CSS. In gritter-notice-wrapper
