### ISSUE TITLE
Tag 1.7.4 release

### ISSUE THREAD

**Issue by dfreeman** [jboesch/Gritter#50]
We'd like to use [rails-assets](https://rails-assets.org) to include Gritter in our app, but it requires releases to be tagged in order to be definitively tied to a version when building a gem.

Could you create a `1.7.4` tag for the current state of `master`? Thanks!

**Comment by yamsellem** [comment]
This also works for Bower.
Using a `bower.json` at the root of the project is not enough.
Every release needs a tag so `"dependencies": {"jquery.gritter": "1.7.4"}` can be used in another `bower.json` file.

Thanks.

**Comment by kpx-dev** [comment]
@jboesch can you please help with this? If not can you please assign one of us as a new maintainer?

**Comment by jboesch** [comment]
I'm sorry everyone! I haven't had any time to maintain Gritter. @kienpham2000 I've made you a collaborator on the project - would you be fine with taking over for a bit? I can add a few others if need be as well.

**Comment by kpx-dev** [comment]
@jboesch cool thanks. Tagged. Closing this issue.
