### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by issackelly** [jboesch/Gritter#7]
Hey, I'd love to use this, but there's no license, so I'm breaking copyright law if I do.

I gather that isn't your intent, so maybe just bogard the license from jQuery and change the names/dates (dual GPL/MIT is an excellent choice for me :)

Cheers.

**Comment by myusuf3** [comment]
https://github.com/jboesch/Gritter/blob/master/js/jquery.gritter.min.js#L5

Its in the actual js file. :)

**Comment by issackelly** [comment]
Woot! Thanks, I had looked all over the site/repo for it... didn't check the source.
